# 新浪财经爬虫配置

crawler:
  name: sina
  display_name: 新浪财经
  enabled: true
  
request:
  base_url: https://finance.sina.com.cn/
  list_urls:
    - https://finance.sina.com.cn/roll/index.d.html?cid=56589&page=1
    - https://finance.sina.com.cn/roll/index.d.html?cid=56589&page=2
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
  timeout: 10
  retry_times: 3
  retry_interval: 5

parser:
  list:
    title_selector: .list_009 li a
    url_selector: .list_009 li a
    date_selector: .time
  detail:
    title_selector: .main-title
    content_selector: .article-content
    date_selector: .date-source span
    author_selector: .author
    source_selector: .source

storage:
  database_path: app/data/sina.db
  save_to_json: true
  json_path: app/data/sina_news.json
  save_full_content: true
  save_images: true
  
monitoring:
  log_level: INFO
  notification: true
  error_alert: true
  performance_tracking: false

scheduler:
  interval: 1800  # 单位：秒
  start_time: "06:00"
  end_time: "23:00"
  crawl_latest_first: true
  max_pages_per_run: 5 